/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'indigo': {
          '100': '#e0e7ff',
          '500': '#6366f1',
          '600': '#4f46e5',
          '700': '#4338ca',
        },
        'gray': {
          '50': '#f9fafb',
          '500': '#6b7280',
          '600': '#4b5563',
          '700': '#374151',
          '800': '#1f2937',
          '900': '#111827',
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'min-h-screen',
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'bg-gray-50',
    'py-12',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'max-w-md',
    'w-full',
    'space-y-8',
    'text-center',
    'text-3xl',
    'font-extrabold',
    'text-gray-900',
    'text-sm',
    'text-gray-600',
    'relative',
    'group',
    'border',
    'border-transparent',
    'rounded-md',
    'bg-indigo-600',
    'hover:bg-indigo-700',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-indigo-500',
  ],
} 